import '@repo/ui/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Docs',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className="sm:flex sm:justify-center">
        <div className="sm:max-w-md w-full h-full">{children}</div>
      </body>
    </html>
  );
}
